spring:
  application:
    name: emailSendToHR
  datasource:
    url: jdbc:mysql://localhost:3306/emailSendToHRDB
    username: root
    password: AnooP@91025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: anoop91098@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  imap:
    host: imap.gmail.com
    port: 993
    username: anoop91098@gmail.com
    password: 
    ssl:
      enable: true
    store:
      protocol: imaps
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  



app:
  message:
    welcome: <h1>Good Moring</h1>